version: "3.8"

services:
  telegram-bot:
    build:
      context: ./HealthBot
      network: host
    container_name: healthbot
    env_file:
      - ./.env
    environment:
      API_HOST: "backend"
    depends_on:
      - database
      - backend
    volumes:
      - ./HealthBot/data:/app/data
    restart: always

  backend:
    build:
      context: ./HealthBackend
      network: host
    container_name: healthbackend
    env_file:
      - ./.env
    environment:
      DB_HOST: "database"
    ports:
      - "${API_PORT}:${API_PORT}"
    command: [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "${API_PORT}" ]
    depends_on:
      - database
    restart: always

  database:
    image: postgres:17
    container_name: healthdb
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: always
  database_test:
    container_name: healthdb_test
    extends:
      service: database
    ports: !override
      - "${TEST_DB_PORT}:5432"
    volumes:
      - ./test_data:/var/lib/postgresql/data
