"""empty message

Revision ID: 2d31706576d9
Revises: 32d815f379f8
Create Date: 2025-01-02 19:40:40.788288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2d31706576d9'
down_revision: Union[str, None] = '32d815f379f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('diseases', 'treatment_plan',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('diseases', 'date_to',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('diseases', 'date_to',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('diseases', 'treatment_plan',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
