"""added_doctor_id

Revision ID: 05f7f628939b
Revises: 10126b3fe3d9
Create Date: 2025-01-25 01:32:51.727375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05f7f628939b'
down_revision: Union[str, None] = '10126b3fe3d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('doctor_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['doctor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'doctor_id')
    # ### end Alembic commands ###
