"""notifications_message_rename

Revision ID: 03b796ec7de8
Revises: efd40c649729
Create Date: 2025-01-30 21:32:47.967590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03b796ec7de8'
down_revision: Union[str, None] = 'efd40c649729'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('message', sa.String(), nullable=True))
    op.drop_column('notifications', 'medicine_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('medicine_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('notifications', 'message')
    # ### end Alembic commands ###
