"""notifications_start_date_add

Revision ID: 98ef05c19835
Revises: 03b796ec7de8
Create Date: 2025-01-30 21:54:18.199293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98ef05c19835'
down_revision: Union[str, None] = '03b796ec7de8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('start_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'start_date')
    # ### end Alembic commands ###
