"""notifications add is_patient

Revision ID: 49bdbb0376a4
Revises: 98ef05c19835
Create Date: 2025-02-20 21:38:32.827503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49bdbb0376a4'
down_revision: Union[str, None] = '98ef05c19835'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('is_patient', sa.Boolean(), server_default='t', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'is_patient')
    # ### end Alembic commands ###
