localization = {
    # REGISTRATION
    "greet_message": "Hello, {}!",
    "language_message": "Select your language:",
    "name_message": "Enter your first and last name:",
    "gender_message": "Select your gender:",
    "gender_list": ["Male", "Female"],
    "weight_message": "Enter your weight:",
    "weight_error_message": "Specify the weight in number format!",
    "height_message": "Enter your height in centimeters (e.g., 160):",
    "height_error_message": "Specify the height in number format!",
    "register_complete_message": "Registration complete!",

    # Personal Data
    "change_data_message": "Edit your information",
    "name_field": "Name",
    "gender_field": "Gender",
    "weight_field": "Weight",
    "height_field": "Height",
    "language_field": "Language",
    "check_personal_data": "View your information",
    "user_info_message": "Your name: {}\nYour gender: {}\nYour language: {}\nYour weight: {}\nYour height: {}",
    "change_info_message": "Select the field you want to change:",
    "enter_new_data_for_change_message": "Enter new data for the field <b>{}</b>",
    "user_change_data_success_message": "The data has been updated successfully!",

    # BUTTONS
    "main_menu_message": "Main Menu",
    "back_button": "Back",
    "to_main_menu_button": "To Main Menu",
    "add_disease_button": "Add a disease",
    "get_diseases_button": "View all diseases",
    "yes_button": "Yes",
    "no_button": "No",

    # DISEASES
    "add_disease_message": "What are you suffering from?",
    "disease_description_message": "Describe your illness (symptoms, complications, anything useful for the doctor)",
    "disease_treatment_plan_message": "If you have a treatment plan, write it:",
    "disease_date_start_message": "When did you get sick? (enter in the format 21.10.2024)",
    "disease_date_end_message": "When did you recover? (enter in the format 21.10.2024)",
    "disease_incorrect_date": "You entered the date in an incorrect format, please enter in the format DD.MM.YYYY - 21.10.2024",
    "disease_still_sick_message": "Are you still sick?",
    "disease_add_success_message": "Disease successfully added!",
    "get_diseases_message": "Here is a list of all your diseases:\n{}",
    "get_diseases_empty_message": "I don't know any of your illnesses!\nYou are healthy!",
    "disease_choose_inline_tip": "Enter your disease or select from the list",
    "disease_date_choose_inline_tip": "Enter the date or select from the list",
    "disease_today_date_word": "Today",
    "disease_yesterday_date_word": "Yesterday",
    "default_diseases_list": ["ARVI", "Flu", "Allergy", "Fracture", "CVD"],
}
