localization = {
    "system_clear_keyboard": "Очищаю клавиатуру...",

    # РЕГИСТРАЦИЯ
    "greet_message": "Привет, {}!",
    "language_message": "Выберите ваш язык:",
    "name_message": "Введите ваше имя и фамилию:",
    "gender_message": "Выберите ваш пол:",
    "gender_list": ["Мужчина", "Женщина"],
    "weight_message": "Введите ваш вес:",
    "weight_error_message": "Укажите вес в формате числа!",
    "height_message": "Введите ваш рост в сантиметрах (пр. 160):",
    "height_error_message": "Укажите рост в формате числа!",
    "register_complete_message": "Регистрация завершена!",

    # Персональные данные
    "change_data_message": "Изменить свои данные",
    "name_field": "Имя",
    "gender_field": "Пол",
    "weight_field": "Вес",
    "height_field": "Рост",
    "language_field": "Язык",
    "check_personal_data": "Посмотреть свои данные",
    "user_info_message": "Ваше имя: {}\nВаш пол: {}\nВаш язык: {}\nВаш вес: {}\nВаш рост: {}",
    "change_info_message": "Выберите поле, которое хотите поменять:",
    "enter_new_data_for_change_message": "Введите новые данные для поля <b>{}</b>",
    "user_change_data_success_message": "Данные успешно обновлены!",
    # КНОПКИ
    "main_menu_message": "Главное меню",
    "back_button": "Назад",
    "to_main_menu_button": "В главное меню",
    "add_disease_button": "Добавить болезнь",
    "get_diseases_button": "Посмотреть все болезни",
    "yes_button": "Да",
    "no_button": "Нет",

    # БОЛЕЗНИ
    "add_disease_message": "Чем вы болеете?",
    "disease_description_message": "Опишите вашу болезнь (симптомы, осложнения, все что полезно врачу)",
    "disease_treatment_plan_message": "Если у вас есть план лечения напишите его:",
    "disease_date_start_message": "Когда заболели? (введите в формате 21.10.2024)",
    "disease_date_end_message": "Когда выздоровели? (введите в формате 21.10.2024)",
    "disease_incorrect_date": "Вы ввели дату в неверном формате, пожалуйста, введите в формате ДД.ММ.ГГГГ - 21.10.2024",
    "disease_still_sick_message": "До сих пор болеете?",
    "disease_add_success_message": "Болезнь успешно добавлена!",
    "get_diseases_message": "Вот список всех ваших болезней:\n{}",
    "disease_choose_inline_tip": "Введите свою болезнь или выберите из списка",
    "disease_date_choose_inline_tip": "Введите дату или выберите из списка",
    "disease_today_date_word": "Сегодня",
    "disease_yesterday_date_word": "Вчера",
    "default_diseases_list": ["ОРВИ", "Грипп", "Аллергия", "Перелом", "ССЗ"],
}
