name: Deployment Workflow
on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy to server
        uses: D3rHase/ssh-command-action@v0.2.2
        with:
          host: ${{secrets.SERVER_IP}}
          user: ${{secrets.SSH_USER}}
          private_key: ${{secrets.SSH_PRIVATE_KEY}}
          # host_fingerprint: ${{ secrets.HOST_FINGERPRINT }}
          command: |
            echo "Начинаю деплой...";
            cd ${{ secrets.WORK_DIR }};
            docker compose down;
            git checkout ${{ secrets.MAIN_BRANCH }};
            git pull;
            echo "Сборка контейнеров.";
            docker compose build telegram-bot database backend nginx;
            echo "Применение миграций";
            docker compose up -d database;
            docker compose run backend alembic upgrade head;
            echo "Запуск контейнеров";
            docker compose up -d telegram-bot database backend nginx;
            echo "Деплой прошел успешно";
      - name: cleanup
          
        run: |
          echo "Очищаю за собой..."
          rm -rf ~/.ssh
